name: chall2026-first-contact

services:
  first-contact:
    image: athack-ctf/chall2026-first-contact:latest
    container_name: chall2026-first-contact
    build:
      context: .
      dockerfile: source/Dockerfile
    ports:
      - "53007:5000"